#include <stdio.h>
#define add(a, b) a += b
#define mul(a, b) a *= b
#define mod(a, b) a %= b
#define div(a, b) a /= b
#define inp(a) a = (int)getchar()
#define eql(a, b) a = a == b

int main(void) {
    // init vars
    int w, x, y, z;
    w = x = y = z = 0;

    /**
     * Begin copy-pasted program
     */

    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 14);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 12);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 13);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 6);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 12);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 4);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 14);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 5);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 13);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 0);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -7);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 4);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -13);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 15);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 10);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 14);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -7);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 6);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 1);
    add(x, 11);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 14);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -9);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 8);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -2);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 5);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -9);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 14);
    mul(y, x);
    add(z, y);
    inp(w);
    mul(x, 0);
    add(x, z);
    mod(x, 26);
    div(z, 26);
    add(x, -14);
    eql(x, w);
    eql(x, 0);
    mul(y, 0);
    add(y, 25);
    mul(y, x);
    add(y, 1);
    mul(z, y);
    mul(y, 0);
    add(y, w);
    add(y, 4);
    mul(y, x);
    add(z, y);

    /**
     * End copy-pasted program
     */

    printf("z = %d", z);
}
